enabled: true
additional_trustees:
  - ericharper
  - ko3n1g
  - chtruong814
  - thomasdhc
  - pablo-garay
  - ayushdg
  - praateekmahajan
  - sarahyurick
  - singhva
  - VibhuJawa
  - arhamm1
  - suiyoubi
  - abhinavg4
  - huvunvidia
additional_vetters:
  - ericharper
  - ko3n1g
  - chtruong814
  - thomasdhc
  - pablo-garay
  - ayushdg
  - praateekmahajan
  - sarahyurick
  - singhva
  - VibhuJawa
  - arhamm1
  - suiyoubi
  - abhinavg4
  - huvunvidia
auto_sync_draft: false
auto_sync_ready: true
