defaults:
  - _self_
  - override hydra/job_logging: none
  - override hydra/hydra_logging: none

hydra:
  run:
    dir: .
  output_subdir: null

raw_data_dir: ???
output_dir: ${raw_data_dir}/result

gpus: 1.0
sample_rate: 48000

enable_vad: true
vad_min_duration_sec: 2.0
vad_max_duration_sec: 60.0
vad_threshold: 0.5

enable_band_filter: true
band_value: full_band

enable_nisqa: true
nisqa_mos_threshold: 4.5
nisqa_noi_threshold: 4.3

enable_sigmos: true
sigmos_noise_threshold: 4.0
sigmos_ovrl_threshold: 3.5

enable_speaker_separation: true
speaker_min_duration: 0.8
speaker_exclude_overlaps: true
