# HARD-NEGATIVE MINING parameters
# base_url: "https://integrate.api.nvidia.com/v1"
model_name: "sentence-transformers/all-MiniLM-L6-v2"
# "intfloat/e5-large-unsupervised"
# "nvdev/nvidia/llama-3.2-nv-embedqa-1b-v1"
# nvdev/nvidia/nv-embedqa-e5-v5"
# "nvdev/nvidia/llama-3.2-nv-embedqa-1b-v1"
model_type: "hf"
query_prefix: "query:"
passage_prefix: "passage:"
api_key: "your api key here"
truncate: "END"
hard_negatives_to_mine: 4
hard_neg_mining_algorithm: "topk_percpos"
percpos: 0.95
# max_hardness_threshold: 0.75
# min_hardness_threshold: 0

# SEMANTIC CLUSTERING parameters
min_cluster_size: 50
max_number_clusters: 200
cluster_output_dir: "/home/viraman/qa_bug_fix/curator_outputs/clusters"
logger_output_dir: "/home/viraman/qa_bug_fix/curator_outputs/logs"
