# Configuration file for semdantic dedup
cache_dir: "/home/ruchaa/projects/nvingest_curator_tutorial/NeMo-Curator/tutorials/multimodal_dapt_curation/code/workspace/semdedup_cache/text" #"workspace/semdedup_cache/text"
num_files: 16

# Embeddings configuration
embedding_model_name_or_path: "sentence-transformers/all-MiniLM-L6-v2"
embedding_batch_size: 128
embeddings_save_loc: "embeddings"
embedding_pooling_strategy: "mean_pooling"
embedding_column: "embeddings"
write_embeddings_to_disk: true
write_to_filename: false

# Clustering configuration
max_iter: 100
n_clusters: 5
clustering_save_loc: "clustering_results"
sim_metric: "cosine"
which_to_keep: "hard"
sort_clusters: true
kmeans_with_cos_dist: false
partition_size: "2gb"

# Extract dedup configuration
eps_thresholds:
  - 0.1
  - 0.01

# Which threshold to use for extracting deduped data
eps_to_extract: 0.1
