# Copyright (c) 2025, NVIDIA CORPORATION. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Generate NeMo Curator image pipeline configuration."""
import argparse
from pathlib import Path


def generate_image_yaml(args: argparse.Namespace) -> str:
    lines = []
    lines.append("# Image Curation Pipeline")
    lines.append("# Generated by NeMo Curator image skill")
    lines.append("")
    lines.append("defaults:")
    lines.append("  - _self_")
    lines.append("  - override hydra/job_logging: none")
    lines.append("  - override hydra/hydra_logging: none")
    lines.append("")
    lines.append("hydra:")
    lines.append("  run:")
    lines.append("    dir: .")
    lines.append("  output_subdir: null")
    lines.append("")
    lines.append(f"input_path: {args.input_path}")
    lines.append(f"output_path: {args.output_path}")
    lines.append(f"model_dir: {args.model_dir or './models'}")
    lines.append("")
    lines.append("stages:")
    lines.append("")

    # File partitioning
    lines.append("  # Stage 1: Partition tar files")
    lines.append("  - _target_: nemo_curator.stages.file_partitioning.FilePartitioningStage")
    lines.append("    file_paths: ${input_path}")
    lines.append(f"    files_per_partition: {args.tar_files_per_partition}")
    lines.append('    file_extensions: [".tar"]')
    lines.append("")

    # Image reader
    lines.append("  # Stage 2: Read images")
    lines.append("  - _target_: nemo_curator.stages.image.io.image_reader.ImageReaderStage")
    lines.append(f"    batch_size: {args.batch_size}")
    lines.append("")

    # Embedding
    lines.append("  # Stage 3: Generate CLIP embeddings")
    lines.append("  - _target_: nemo_curator.stages.image.embedders.clip_embedder.ImageEmbeddingStage")
    lines.append("    model_dir: ${model_dir}")
    lines.append(f"    num_gpus_per_worker: {args.embedding_gpus}")
    lines.append("")

    # Aesthetic filter
    if args.aesthetic_threshold:
        lines.append("  # Stage 4: Aesthetic filtering")
        lines.append("  - _target_: nemo_curator.stages.image.filters.aesthetic_filter.ImageAestheticFilterStage")
        lines.append("    model_dir: ${model_dir}")
        lines.append(f"    score_threshold: {args.aesthetic_threshold}")
        lines.append(f"    num_gpus_per_worker: {args.filter_gpus}")
        lines.append("")

    # NSFW filter
    if args.nsfw_threshold:
        lines.append("  # Stage 5: NSFW filtering")
        lines.append("  - _target_: nemo_curator.stages.image.filters.nsfw_filter.ImageNSFWFilterStage")
        lines.append("    model_dir: ${model_dir}")
        lines.append(f"    score_threshold: {args.nsfw_threshold}")
        lines.append(f"    num_gpus_per_worker: {args.filter_gpus}")
        lines.append("")

    # Deduplication
    if args.dedup:
        lines.append("  # Stage 6: Deduplication")
        lines.append("  - _target_: nemo_curator.stages.image.deduplication.removal.ImageDuplicatesRemovalStage")
        lines.append("")

    # Writer
    lines.append("  # Final Stage: Write images")
    lines.append("  - _target_: nemo_curator.stages.image.io.image_writer.ImageWriterStage")
    lines.append("    output_dir: ${output_path}")
    lines.append(f"    images_per_tar: {args.images_per_tar}")

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate image pipeline config")
    parser.add_argument("--input-path", "-i", required=True)
    parser.add_argument("--output-path", "-o", required=True)
    parser.add_argument("--output-file", "-f", default="image_pipeline.yaml")
    parser.add_argument("--model-dir")
    parser.add_argument("--batch-size", type=int, default=100)
    parser.add_argument("--tar-files-per-partition", type=int, default=1)
    parser.add_argument("--aesthetic-threshold", type=float, default=0.5)
    parser.add_argument("--no-aesthetic", action="store_const", const=None, dest="aesthetic_threshold")
    parser.add_argument("--nsfw-threshold", type=float, default=0.5)
    parser.add_argument("--no-nsfw", action="store_const", const=None, dest="nsfw_threshold")
    parser.add_argument("--dedup", action="store_true", default=False)
    parser.add_argument("--embedding-gpus", type=float, default=0.25)
    parser.add_argument("--filter-gpus", type=float, default=0.25)
    parser.add_argument("--images-per-tar", type=int, default=100)
    args = parser.parse_args()

    yaml_content = generate_image_yaml(args)
    Path(args.output_file).write_text(yaml_content)

    print(f"Generated: {args.output_file}")
    print(f"Run: python -m nemo_curator.config.run --config-path=. --config-name={Path(args.output_file).stem}")


if __name__ == "__main__":
    main()
