#!/usr/bin/env python3
# Copyright (c) 2025, NVIDIA CORPORATION. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Generate NeMo Curator pipeline YAML configuration for data curation.

This script generates Hydra-compatible YAML configurations for various
curation workflows including text, video, image, and audio processing.

Examples:
    # Generate text curation config
    python generate_yaml.py \\
        --modality text \\
        --input-path /data/raw \\
        --output-path /data/curated \\
        --output-file text_curation.yaml

    # Generate video curation config with captioning
    python generate_yaml.py \\
        --modality video \\
        --input-path /data/videos \\
        --output-path /data/clips \\
        --caption \\
        --output-file video_curation.yaml
"""
import argparse
import json
import sys
from pathlib import Path

# Filter presets
FILTER_PRESETS = {
    "minimal": [
        ("WordCountFilter", {"min_words": 50, "max_words": 100000}),
        ("NonAlphaNumericFilter", {"max_non_alpha_numeric_to_text_ratio": 0.25}),
    ],
    "standard": [
        ("WordCountFilter", {"min_words": 50, "max_words": 100000}),
        ("NonAlphaNumericFilter", {"max_non_alpha_numeric_to_text_ratio": 0.25}),
        ("SymbolsToWordsFilter", {"max_symbol_to_word_ratio": 0.1}),
        ("NumbersFilter", {"max_number_to_text_ratio": 0.15}),
        ("UrlsFilter", {"max_url_to_text_ratio": 0.2}),
        ("BulletsFilter", {"max_bullet_lines_ratio": 0.9}),
        ("WhiteSpaceFilter", {"max_white_space_ratio": 0.25}),
        ("MeanWordLengthFilter", {"min_mean_word_length": 3, "max_mean_word_length": 10}),
        ("RepeatedLinesFilter", {"max_repeated_line_fraction": 0.3}),
        ("RepeatedParagraphsFilter", {"max_repeated_paragraphs_ratio": 0.3}),
        ("PunctuationFilter", {"max_punctuation_ratio": 0.1}),
        ("EllipsisFilter", {"max_ellipsis_ratio": 0.3}),
        ("CommonEnglishWordsFilter", {"min_num_common_words": 2}),
        ("WordsWithoutAlphabetsFilter", {"max_words_without_alphabets_ratio": 0.5}),
        ("PornographicUrlsFilter", {}),
    ],
    "full": [
        ("WordCountFilter", {"min_words": 50, "max_words": 100000}),
        ("NonAlphaNumericFilter", {"max_non_alpha_numeric_to_text_ratio": 0.25}),
        ("SymbolsToWordsFilter", {"max_symbol_to_word_ratio": 0.1}),
        ("NumbersFilter", {"max_number_to_text_ratio": 0.15}),
        ("UrlsFilter", {"max_url_to_text_ratio": 0.2}),
        ("BulletsFilter", {"max_bullet_lines_ratio": 0.9}),
        ("WhiteSpaceFilter", {"max_white_space_ratio": 0.25}),
        ("ParenthesesFilter", {"max_parentheses_ratio": 0.1}),
        ("LongWordFilter", {"max_long_word_ratio": 0.1}),
        ("MeanWordLengthFilter", {"min_mean_word_length": 3, "max_mean_word_length": 10}),
        ("RepeatedLinesFilter", {"max_repeated_line_fraction": 0.3}),
        ("RepeatedParagraphsFilter", {"max_repeated_paragraphs_ratio": 0.3}),
        ("RepeatedLinesByCharFilter", {"max_repeated_lines_char_ratio": 0.2}),
        ("RepeatedParagraphsByCharFilter", {"max_repeated_paragraphs_char_ratio": 0.2}),
        ("RepeatingTopNGramsFilter", {}),
        ("RepeatingDuplicateNGramsFilter", {}),
        ("PunctuationFilter", {"max_punctuation_ratio": 0.1}),
        ("EllipsisFilter", {"max_ellipsis_ratio": 0.3}),
        ("CommonEnglishWordsFilter", {"min_num_common_words": 2}),
        ("WordsWithoutAlphabetsFilter", {"max_words_without_alphabets_ratio": 0.5}),
        ("PornographicUrlsFilter", {}),
    ],
}


def generate_text_config(
    input_path: str,
    output_path: str,
    filters: str = "standard",
    classify: list[str] | None = None,
    edu_filter: int | None = None,
    dedup: str | None = "fuzzy",
    cache_path: str | None = None,
) -> str:
    """Generate text curation pipeline configuration."""
    if cache_path is None:
        cache_path = f"{output_path}/.cache"

    lines = [
        "# Text Curation Pipeline Configuration",
        "# Generated by CURATOR-OS curate skill",
        "#",
        "# Run with:",
        "#   python -m nemo_curator.config.run --config-path=. --config-name=<filename>",
        "",
        "defaults:",
        "  - _self_",
        "  - override hydra/job_logging: none",
        "  - override hydra/hydra_logging: none",
        "",
        "hydra:",
        "  run:",
        "    dir: .",
        "  output_subdir: null",
        "",
        "# I/O Configuration",
        f'input_path: "{input_path}"',
        f'output_path: "{output_path}"',
        f'cache_path: "{cache_path}"',
        'text_field: "text"',
        "",
        "# Ray Client",
        "ray_client:",
        "  _target_: nemo_curator.core.client.RayClient",
        "  num_cpus: null",
        "  num_gpus: 4",
        "",
        "# Pipeline Stages",
        "stages:",
        "",
        "  # 1. Read Data",
        "  - _target_: nemo_curator.stages.text.io.reader.ParquetReader",
        "    file_paths: ${input_path}",
        "",
    ]

    # Add filters
    if filters and filters != "none":
        filter_list = FILTER_PRESETS.get(filters, FILTER_PRESETS["standard"])
        lines.append(f"  # 2. Heuristic Filtering ({len(filter_list)} filters)")
        for filter_name, params in filter_list:
            lines.append(f"  - _target_: nemo_curator.stages.text.modules.ScoreFilter")
            lines.append(f"    filter_obj:")
            lines.append(f"      _target_: nemo_curator.stages.text.filters.{filter_name}")
            for k, v in params.items():
                lines.append(f"      {k}: {v}")
            lines.append(f"    text_field: ${{text_field}}")
            lines.append("")

    # Add classifiers
    if classify:
        lines.append("  # 3. Quality Classification")
        for classifier in classify:
            if classifier == "quality":
                lines.append("  - _target_: nemo_curator.stages.text.classifiers.QualityClassifier")
                lines.append("    batch_size: 64")
                lines.append("")
            elif classifier == "edu":
                lines.append("  - _target_: nemo_curator.stages.text.classifiers.FineWebEduClassifier")
                lines.append("    batch_size: 32")
                lines.append("")
            elif classifier == "domain":
                lines.append("  - _target_: nemo_curator.stages.text.classifiers.DomainClassifier")
                lines.append("    batch_size: 64")
                lines.append("")

    # Add edu filter if specified
    if edu_filter is not None:
        lines.append(f"  # Filter by educational score >= {edu_filter}")
        lines.append("  - _target_: nemo_curator.stages.text.modules.ScoreFilter")
        lines.append("    score_field: edu_score")
        lines.append(f"    threshold: {edu_filter}")
        lines.append("")

    # Add deduplication as a separate workflow
    if dedup and dedup != "none":
        lines.append("  # 4. Write intermediate (before dedup)")
        lines.append("  - _target_: nemo_curator.stages.text.io.writer.ParquetWriter")
        lines.append('    output_path: "${output_path}/pre_dedup"')
        lines.append("")
        lines.append("# Deduplication (run separately)")
        lines.append("# See /dedup-fuzzy skill for FuzzyDeduplicationWorkflow configuration")
        lines.append(f"# dedup_method: {dedup}")
        lines.append("")

    # Final write
    lines.append("  # Final Write")
    lines.append("  - _target_: nemo_curator.stages.text.io.writer.ParquetWriter")
    lines.append("    output_path: ${output_path}")
    lines.append("")

    return "\n".join(lines)


def generate_video_config(
    input_path: str,
    output_path: str,
    clip_method: str = "transnetv2",
    caption: bool = False,
    embed: bool = False,
    filter_motion: bool = True,
) -> str:
    """Generate video curation pipeline configuration."""
    lines = [
        "# Video Curation Pipeline Configuration",
        "# Generated by CURATOR-OS curate skill",
        "",
        "defaults:",
        "  - _self_",
        "  - override hydra/job_logging: none",
        "",
        "hydra:",
        "  run:",
        "    dir: .",
        "  output_subdir: null",
        "",
        f'input_path: "{input_path}"',
        f'output_path: "{output_path}"',
        "",
        "ray_client:",
        "  _target_: nemo_curator.core.client.RayClient",
        "  num_cpus: null",
        "  num_gpus: 4",
        "",
        "stages:",
        "",
        "  # 1. Read Videos",
        "  - _target_: nemo_curator.stages.video.io.video_reader.VideoReader",
        "    input_path: ${input_path}",
        "",
    ]

    # Clipping
    if clip_method == "transnetv2":
        lines.extend([
            "  # 2. Scene Detection (GPU)",
            "  - _target_: nemo_curator.stages.video.clipping.TransNetV2ClipExtractionStage",
            "    # GPU memory: ~16GB",
            "",
        ])
    else:
        lines.extend([
            "  # 2. Fixed Stride Clipping (CPU)",
            "  - _target_: nemo_curator.stages.video.clipping.FixedStrideExtractorStage",
            "    clip_duration: 10.0",
            "    stride: 10.0",
            "",
        ])

    # Motion filtering
    if filter_motion:
        lines.extend([
            "  # 3. Motion Filtering",
            "  - _target_: nemo_curator.stages.video.filtering.MotionVectorDecodeStage",
            "",
            "  - _target_: nemo_curator.stages.video.filtering.MotionFilterStage",
            "    min_motion_threshold: 0.1",
            "",
        ])

    # Captioning
    if caption:
        lines.extend([
            "  # 4. Captioning (GPU)",
            "  - _target_: nemo_curator.stages.video.caption.CaptionPreparationStage",
            "",
            "  - _target_: nemo_curator.stages.video.caption.CaptionGenerationStage",
            "    # Requires: 1 GPU, ~24GB memory",
            "",
        ])

    # Embedding
    if embed:
        lines.extend([
            "  # 5. Embedding (GPU)",
            "  - _target_: nemo_curator.stages.video.embedding.CosmosEmbed1FrameCreationStage",
            "",
            "  - _target_: nemo_curator.stages.video.embedding.CosmosEmbed1EmbeddingStage",
            "    # GPU memory: ~16GB",
            "",
        ])

    # Write
    lines.extend([
        "  # Write Clips",
        "  - _target_: nemo_curator.stages.video.io.ClipWriterStage",
        "    output_path: ${output_path}",
        "",
    ])

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )

    parser.add_argument(
        "--modality",
        required=True,
        choices=["text", "video", "image", "audio"],
        help="Data modality",
    )
    parser.add_argument(
        "--input-path",
        required=True,
        help="Path to input data",
    )
    parser.add_argument(
        "--output-path",
        required=True,
        help="Path for output data",
    )
    parser.add_argument(
        "--output-file",
        help="Write config to file (default: stdout)",
    )

    # Text-specific options
    parser.add_argument(
        "--filters",
        default="standard",
        choices=["none", "minimal", "standard", "full"],
        help="Filter preset (text only, default: standard)",
    )
    parser.add_argument(
        "--classify",
        nargs="+",
        choices=["quality", "edu", "domain"],
        help="Classifiers to run (text only)",
    )
    parser.add_argument(
        "--edu-filter",
        type=int,
        help="Filter by edu score >= N (text only)",
    )
    parser.add_argument(
        "--dedup",
        default="fuzzy",
        choices=["none", "exact", "fuzzy", "semantic"],
        help="Deduplication method (text only, default: fuzzy)",
    )
    parser.add_argument(
        "--no-dedup",
        action="store_true",
        help="Skip deduplication (text only)",
    )
    parser.add_argument(
        "--cache-path",
        help="Cache path for deduplication (text only)",
    )

    # Video-specific options
    parser.add_argument(
        "--clip-method",
        default="transnetv2",
        choices=["transnetv2", "fixed"],
        help="Clipping method (video only, default: transnetv2)",
    )
    parser.add_argument(
        "--caption",
        action="store_true",
        help="Generate captions (video only)",
    )
    parser.add_argument(
        "--embed",
        action="store_true",
        help="Generate embeddings (video only)",
    )
    parser.add_argument(
        "--no-filter-motion",
        action="store_true",
        help="Skip motion filtering (video only)",
    )

    args = parser.parse_args()

    # Generate config based on modality
    if args.modality == "text":
        dedup = None if args.no_dedup else args.dedup
        config = generate_text_config(
            input_path=args.input_path,
            output_path=args.output_path,
            filters=args.filters,
            classify=args.classify,
            edu_filter=args.edu_filter,
            dedup=dedup,
            cache_path=args.cache_path,
        )
    elif args.modality == "video":
        config = generate_video_config(
            input_path=args.input_path,
            output_path=args.output_path,
            clip_method=args.clip_method,
            caption=args.caption,
            embed=args.embed,
            filter_motion=not args.no_filter_motion,
        )
    else:
        print(json.dumps({"error": f"Config generation for {args.modality} not yet implemented"}))
        sys.exit(1)

    # Output
    if args.output_file:
        Path(args.output_file).write_text(config)
        print(json.dumps({
            "status": "success",
            "file": args.output_file,
            "modality": args.modality,
            "run_command": f"python -m nemo_curator.config.run --config-path=. --config-name={Path(args.output_file).stem}",
        }))
    else:
        print(config)


if __name__ == "__main__":
    main()
