{
 "title": "Xenna Ray Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(ray_cluster_active_nodes,backend)"
    }
   },
   {
    "name": "gpu",
    "label": "GPU",
    "query": {
     "query": "label_values(ray_pipeline_input_tasks{backend=\"$cluster\"},gpu)"
    }
   },
   {
    "name": "function_id",
    "label": "Function_ID",
    "query": {
     "query": "label_values(ray_cluster_active_nodes{backend=~\"$cluster\"},function_id)"
    }
   },
   {
    "name": "session",
    "label": "Session",
    "query": {
     "query": "label_values(ray_cluster_active_nodes,SessionName)"
    }
   },
   {
    "name": "stage",
    "label": "Stage",
    "query": {
     "query": "label_values(ray_pipeline_actor_count{SessionName=\"$session\"},stage)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Default", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pipeline Progress",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max(ray_pipeline_input_tasks{SessionName=~\"${session}\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "max by (stage) (ray_pipeline_finished_tasks_normalized{SessionName=~\"${session}\"})",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "Process Time / Task / Actor",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum by (stage) (ray_pipeline_actor_process_time{SessionName=~\"${session}\"})",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "Actor Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum by (stage) (ray_pipeline_actor_count{state=\"ready\", SessionName=~\"${session}\"})",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "GPU Allocated vs. Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (stage) (\r\n    (max by (stage) (ray_pipeline_stage_gpu_alloc{SessionName=~\"${session}\"}))\r\n    * on (stage) group_left ()\r\n    (max by (stage) (ray_pipeline_actor_count{SessionName=~\"${session}\", state=\"target\"}))   \r\n)",
     "legendFormat": "{{stage}}"
    },
    {
     "expr": "sum (ray_node_gpus_available{SessionName=~\"${session}\"})",
     "legendFormat": "Total Available"
    }
   ]
  },
  {
   "title": "Cross-Stage Data Movement - Avg Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(sum by (stage) (ray_pipeline_stage_deserialize_size{SessionName=~\"${session}\"}))\r\n/ on (stage) group_left ()\r\n(sum by (stage) (ray_pipeline_stage_deserialize_count{SessionName=~\"${session}\"}))",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "Cross-Stage Data Movement - Local Percentage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(max by (stage) (ray_pipeline_schedule_task_count{SessionName=~\"${session}\", affinity=\"local\"}))\r\n/ on (stage) group_left ()\r\n(\r\n    (max by (stage) (ray_pipeline_schedule_task_count{SessionName=~\"${session}\", affinity=\"local\"}))\r\n    + on (stage) group_left ()\r\n    (max by (stage) (ray_pipeline_schedule_task_count{SessionName=~\"${session}\", affinity=\"remote\"}))\r\n)",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "Comm / Compute Ratio",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by (stage) (ray_pipeline_stage_deserialize_time{SessionName=~\"${session}\"}))\r\n/ on (stage) group_left ()\r\n(sum by (stage) (ray_pipeline_stage_process_time{SessionName=~\"${session}\"}))",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "GPU Stage Worker Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum (\r\n    (max by (stage) (ray_pipeline_stage_gpu_alloc{SessionName=~\"${session}\"}))\r\n    * on (stage) group_left ()\r\n    (max by (stage) (ray_pipeline_actor_count{SessionName=~\"${session}\", state=\"running\"}))\r\n)\r\n/ on (stage) group_left\r\nsum (\r\n    (max by (stage) (ray_pipeline_stage_gpu_alloc{SessionName=~\"${session}\"}))\r\n    * on (stage) group_left ()\r\n    (max by (stage) (ray_pipeline_actor_count{SessionName=~\"${session}\", state=\"ready\"}))\r\n    \r\n)",
     "legendFormat": "GPU Stage Workers"
    }
   ]
  },
  {
   "title": "GPU Utilization per Stage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (stage) (\r\n    ray_pipeline_stage_gpu_alloc{SessionName=~\"${session}\"} * on (SessionName, NodeAddress, GpuIndex) group_left\r\n    label_replace(ray_node_gpus_utilization{SessionName=~\"${session}\"}, \"NodeAddress\",\"$1\",\"ip\", \"(.+)\")\r\n)",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(ray_node_gpus_utilization{SessionName=~\"${session}\"})",
     "legendFormat": "avg"
    },
    {
     "expr": "avg(\r\n    avg_over_time(\r\n        ray_node_gpus_utilization{SessionName=~\"${session}\"}[5m]\r\n    )\r\n)",
     "legendFormat": "5m-smooth"
    }
   ]
  },
  {
   "title": "GPU Memory per Stage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "avg by (stage) (\r\n    ray_pipeline_stage_gpu_alloc{SessionName=~\"${session}\"} * on (SessionName, NodeAddress, GpuIndex) group_left\r\n    label_replace(ray_node_gram_used{SessionName=~\"${session}\"}, \"NodeAddress\",\"$1\",\"ip\", \"(.+)\")\r\n)",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "CPU Allocation per Stage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (stage) (ray_pipeline_stage_cpu_alloc{SessionName=~\"${session}\"})",
     "legendFormat": "{{stage}}"
    },
    {
     "expr": "sum (ray_pipeline_stage_cpu_alloc{SessionName=~\"${session}\"})",
     "legendFormat": "Total Allocated"
    },
    {
     "expr": "sum(ray_node_cpu_count{SessionName=~\"${session}\"})",
     "legendFormat": "Total Available"
    }
   ]
  },
  {
   "title": "CPU Usage per Stage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (stage) (ray_pipeline_actor_resource_usage{SessionName=~\"${session}\", stage!=\"\", resource=\"cpu\"}) / 100",
     "legendFormat": "{{stage}}"
    },
    {
     "expr": "sum(ray_node_cpu_count{SessionName=~\"${session}\"})",
     "legendFormat": "Total Available"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (instance) (ray_node_cpu_utilization{SessionName=~\"${session}\"})",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "avg (\r\n    avg_over_time (ray_node_cpu_utilization{SessionName=~\"${session}\"}[1h]\r\n    )\r\n)",
     "legendFormat": "Avg-1h"
    },
    {
     "expr": "avg (\r\n    avg_over_time (ray_node_cpu_utilization{SessionName=~\"${session}\"}[8h]\r\n    )\r\n)",
     "legendFormat": "Avg-8h"
    }
   ]
  },
  {
   "title": "CPU Usage per Actor",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(\r\n    sum by (stage) (ray_pipeline_actor_resource_usage{SessionName=~\"${session}\", stage!=\"\", resource=\"cpu\"})\r\n)\r\n/ on (stage)\r\n(\r\n    sum by (stage) (ray_pipeline_actor_count{SessionName=~\"${session}\", state=\"running\"})\r\n)\r\n/ 100",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "System Memory Usage per Stage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (stage) (ray_pipeline_actor_resource_usage{SessionName=~\"${session}\", stage!=\"\", resource=\"memory\"})",
     "legendFormat": "{{stage}}"
    },
    {
     "expr": "sum(ray_node_mem_total{SessionName=~\"${session}\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "System Memory Usage per Node",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (ray_node_mem_used{SessionName=~\"${session}\"})",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "avg(ray_node_mem_total{SessionName=~\"${session}\"})",
     "legendFormat": "total-avail"
    }
   ]
  },
  { "title": "Actor Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Actor Pool - $stage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
   "repeat": "stage",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (stage, state) (ray_pipeline_actor_count{SessionName=~\"${session}\", state!=\"ready\", state!=\"pending\", stage=\"${stage}\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "Actor Pool Queuing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Actor Pool Queues - $stage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "repeat": "stage",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (stage, state) (ray_pipeline_input_queue_size{SessionName=~\"${session}\", stage=\"${stage}\"})",
     "legendFormat": "input-queue"
    },
    {
     "expr": "sum by (stage, state) (ray_pipeline_slots_used{SessionName=~\"${session}\", stage=\"${stage}\"})",
     "legendFormat": "slots-used"
    },
    {
     "expr": "sum by (stage, state) (ray_pipeline_slots_empty{SessionName=~\"${session}\", stage=\"${stage}\"})",
     "legendFormat": "slots-empty"
    },
    {
     "expr": "sum by (stage, state) (ray_pipeline_output_queue_size{SessionName=~\"${session}\", stage=\"${stage}\"})",
     "legendFormat": "output-queue"
    }
   ]
  },
  { "title": "Ray Internals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Ray Spilled",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(ray_spill_manager_objects_bytes{SessionName=~\"${session}\", State=\"Spilled\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Ray Object Store Used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (ray_object_store_used_memory{SessionName=~\"${session}\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Ray Object Store Available",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (ray_object_store_available_memory{SessionName=~\"${session}\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Ray Object Manager Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance, Type) (ray_object_manager_bytes{SessionName=~\"${session}\"})",
     "legendFormat": "{{instance}}-{{Type}}"
    }
   ]
  }
 ]
}