root: '/ads_ds3/data/SemDeDup_BenchMark'
sample: 12 # todo name to num_samples
id_col:
   name: 'adlr_id' # 'id' #'adlr_id'
   type: 'str' # 'int' #'str'

# Embeddings
embeddings:
  input_column: 'text'
  input_data_dir: '/datasets/prospector-lm/cleaned_exact_dedup_all_cc'
  output_data_dir: '/raid/vjawa/prospector-lm/embeddings_crossfit_fb_c4_10'
  path_or_name: 'facebook/opt-125m'
  emb_size: 768
  batch_size: 512

clustering:
  save_loc: "results_fbopt_nc_11_crossfit" #"results_fbopt125_cc_crossfit_5"
  #save_loc: "results_crossfit_fb_c4_10a"
  num_clusters: 1000 # -- number of clusters
  seed: 1234
  niter: 100
  # Kmeans can only be done with L2 using cuML.
  Kmeans_with_cos_dist: False # Only False allowed


semdedup:
  # -- which example to keep from each group of duplicates
  which_to_keep: "hard"
  # largest cluster size the memory is large enough to process. If the
  # cluster size is larger than it, we will devide the cluster into small
  # clusters and process each one separately.
  largest_cluster_size_to_process: 100000
  sim_metric: "cosine" # Only cosine is allowed.

extract_dedup:
  use_eps_from_yml: True
  eps:  0.01 0.001
