# Text Quick Pass Pipeline - TEST CONFIG
# Pre-configured to run with sample_data/
#
# Usage:
#   cd example-skill-gen
#   python -m nemo_curator.config.run --config-path=. --config-name=text_quick_pass_test

defaults:
  - _self_
  - override hydra/job_logging: none
  - override hydra/hydra_logging: none

hydra:
  run:
    dir: .
  output_subdir: null

# Pre-configured paths for testing
input_path: sample_data/input.jsonl
output_path: sample_data/output
text_field: "text"

# Ray Client Configuration
ray_client:
  _target_: nemo_curator.core.client.RayClient
  num_cpus: null
  num_gpus: 0

# Pipeline Stages
stages:

  # Stage 1: Read JSONL
  - _target_: nemo_curator.stages.text.io.reader.JsonlReader
    file_paths: ${input_path}

  # Stage 2: Minimal Filtering

  # Filter 1: Word count (50-100K words)
  - _target_: nemo_curator.stages.text.modules.ScoreFilter
    filter_obj:
      _target_: nemo_curator.stages.text.filters.WordCountFilter
      min_words: 50
      max_words: 100000
    text_field: ${text_field}

  # Filter 2: Non-alphanumeric ratio (< 25%)
  - _target_: nemo_curator.stages.text.modules.ScoreFilter
    filter_obj:
      _target_: nemo_curator.stages.text.filters.NonAlphaNumericFilter
      max_non_alpha_numeric_to_text_ratio: 0.25
    text_field: ${text_field}

  # Stage 3: Write Output
  - _target_: nemo_curator.stages.text.io.writer.ParquetWriter
    output_path: ${output_path}
