# Copyright (c) 2025, NVIDIA CORPORATION. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Generate NeMo Curator audio pipeline configuration."""
import argparse
from pathlib import Path


def generate_audio_yaml(args: argparse.Namespace) -> str:
    lines = []
    lines.append("# Audio Curation Pipeline")
    lines.append("# Generated by NeMo Curator audio skill")
    lines.append("")
    lines.append("defaults:")
    lines.append("  - _self_")
    lines.append("  - override hydra/job_logging: none")
    lines.append("  - override hydra/hydra_logging: none")
    lines.append("")
    lines.append("hydra:")
    lines.append("  run:")
    lines.append("    dir: .")
    lines.append("  output_subdir: null")
    lines.append("")
    lines.append(f"input_path: {args.input_path}")
    lines.append(f"output_path: {args.output_path}")
    lines.append(f"model_name: {args.model_name}")
    lines.append(f"wer_threshold: {args.wer_threshold}")
    lines.append(f"gpu_memory_gb: {args.gpu_memory_gb}")
    lines.append("")
    lines.append("stages:")
    lines.append("")

    # ASR Inference
    lines.append("  # Stage 1: ASR Inference")
    lines.append("  - _target_: nemo_curator.stages.audio.inference.asr_nemo.InferenceAsrNemoStage")
    lines.append("    model_name: ${model_name}")
    if args.gpu_memory_gb > 0:
        lines.append("    resources:")
        lines.append("      _target_: nemo_curator.stages.resources.Resources")
        lines.append("      cpus: 1.0")
        lines.append("      gpu_memory_gb: ${gpu_memory_gb}")
    lines.append("")

    # WER Calculation
    lines.append("  # Stage 2: Calculate WER")
    lines.append("  - _target_: nemo_curator.stages.audio.metrics.get_wer.GetPairwiseWerStage")
    lines.append("    text_key: text")
    lines.append("    pred_text_key: pred_text")
    lines.append("    wer_key: wer")
    lines.append("")

    # Duration
    lines.append("  # Stage 3: Get Audio Duration")
    lines.append("  - _target_: nemo_curator.stages.audio.common.GetAudioDurationStage")
    lines.append("    audio_filepath_key: audio_filepath")
    lines.append("    duration_key: duration")
    lines.append("")

    # Filter by WER
    lines.append("  # Stage 4: Filter by WER threshold")
    lines.append("  - _target_: nemo_curator.stages.audio.common.PreserveByValueStage")
    lines.append("    input_value_key: wer")
    lines.append("    target_value: ${wer_threshold}")
    lines.append('    operator: "le"')
    lines.append("")

    # Convert to Document
    lines.append("  # Stage 5: Convert to Document format")
    lines.append("  - _target_: nemo_curator.stages.audio.io.convert.AudioToDocumentStage")
    lines.append("")

    # Writer
    lines.append("  # Stage 6: Write output")
    lines.append("  - _target_: nemo_curator.stages.text.io.writer.jsonl.JsonlWriter")
    lines.append("    path: ${output_path}")

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate audio pipeline config")
    parser.add_argument("--input-path", "-i", required=True, help="Path to input audio manifest or directory")
    parser.add_argument("--output-path", "-o", required=True, help="Path for output JSONL files")
    parser.add_argument("--output-file", "-f", default="audio_pipeline.yaml", help="Output YAML config filename")
    parser.add_argument("--model-name", required=True, help="NeMo ASR model name (e.g., nvidia/stt_en_fastconformer_hybrid_large_pc)")
    parser.add_argument("--wer-threshold", type=float, default=75.0, help="Max WER percentage to keep (0-100)")
    parser.add_argument("--gpu-memory-gb", type=float, default=16.0, help="GPU memory in GB for ASR (0 for CPU-only)")
    args = parser.parse_args()

    yaml_content = generate_audio_yaml(args)
    Path(args.output_file).write_text(yaml_content)

    print(f"Generated: {args.output_file}")
    print(f"Run: python -m nemo_curator.config.run --config-path=. --config-name={Path(args.output_file).stem}")


if __name__ == "__main__":
    main()
